@BASE_URL=http://localhost:3000

POST {{BASE_URL}}/api/products
Content-Type: application/json
Authorization: {{accessToken}}

{
    "name": "Grego",
    "code": "2468101",
    "price": 101,
    "qty": 161,
    "description": "grego grego grego",
    "modelName": "Greg 3.0",
    "addonName": "peixo",
    "length": 21,
    "width": 71,
    "height": 61,
    "heightAddon": 91,
    "image1": "aaaaaaaooooo",
    "image2": "bbbbbbbooooo",
    "image3": "cccccccooooo"
}

###

GET  {{BASE_URL}}/api/products
Authorization: {{accessToken}}